name: Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true

# To publish assets to on GitHub release pages
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Create tag
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo } = context.repo;
          await github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{ inputs.tag_name }}',
            sha: context.sha
          })

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # to avoid shadow clone which would impact the version generation
        # See `scripts/gen-version.sh`
        fetch-depth: "0"

    - name: Get version
      id: get-version
      run: |
        echo "version=$(./scripts/gen-version.sh)" >> $GITHUB_OUTPUT

    - name: Build
      run: |
        ./scripts/build.sh --create-tarball

    - name: Run tests
      run: |
        ./scripts/run-tests.sh

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: anbox-streaming-sdk_${{ steps.get-version.outputs.version }}.zip
        tag_name: ${{ steps.get-version.outputs.version }}
